name: C/C++ CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Clang
  # You may pin to the exact commit or the version.
  # uses: egor-tensin/setup-clang@23bc15cd4207e45f1566447deb48f4ff3ef932cb
      uses: tangjiaxin188/setup-clang@master
      with:
            platform: x86_64
            version: 22
    # - name: Install LLVM
    #   run:  apt install llvm -y
    - name: build
      run:  ./build.sh

    
    - name: Package kernel.elf
      run: tar -czf kernel-riscv32.tar.gz kernel.elf
  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: kernel-elf
          path: kernel-riscv32.tar.gz
          if-no-files-found: error   # 如果找不到文件则报错

    
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          kernel-riscv32.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true   # 自动生成 release notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
